# Generated by Django 2.1.7 on 2019-06-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(verbose_name='Issue Found is')),
                ('description', models.TextField(verbose_name='Related Scenario')),
                ('setup_date', models.DateField(default='1991-10-23')),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(auto_now_add=True)),
                ('report_number', models.TextField(verbose_name='Report Number')),
                ('protocol_on_report', models.TextField(verbose_name='Protocol is ')),
                ('report_issue_date', models.DateField(default='1991-10-23')),
                ('lab', models.CharField(choices=[('BV', 'BV'), ('ITS', 'ITS'), ('TUV', 'TUV')], max_length=30)),
                ('pdf_name', models.TextField(verbose_name='PDF name is')),
                ('auditor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditors.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SpecLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speck_number', models.CharField(max_length=30, verbose_name='Speck Number')),
                ('safety_and_regulatory', models.CharField(max_length=30, verbose_name='Safety and Regulatory')),
                ('incorrect_test_method', models.TextField(verbose_name='Incorrect Test Method on Report')),
                ('issue_found', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ReviewStage.IssuePool')),
                ('report_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ReviewStage.ReportInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StatusAndNextStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_cut', models.CharField(default='django flying', max_length=50, verbose_name='In short')),
                ('status', models.TextField(verbose_name='Status')),
                ('next_step', models.TextField(db_column='next_step', verbose_name='Next Step')),
                ('status_description', models.TextField(db_column='status_de', null=True, verbose_name='Status Description')),
                ('next_step_description', models.TextField(db_column='next_de', null=True, verbose_name='Next Step Description')),
                ('setup_date', models.DateField(default='1991-10-23', verbose_name='Setup Date')),
                ('setup_by', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
