# Generated by Django 2.1.7 on 2019-06-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReviewStage', '0001_initial'),
        ('SamplingStage', '0001_initial'),
        ('auditors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='mfp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SamplingStage.MFP'),
        ),
        migrations.AddField(
            model_name='issuepool',
            name='setup_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auditors.Account', verbose_name='Setup by'),
        ),
    ]
