# Generated by Django 2.1.7 on 2019-06-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewStage', '0002_auto_20190614_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusandnextstep',
            name='setup_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auditors.Account'),
        ),
    ]
