# Generated by Django 2.1.7 on 2019-06-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speck_number', models.CharField(default='', max_length=30, null=True, verbose_name='Speck Number')),
                ('regulation', models.TextField(verbose_name='Regulation')),
                ('requirement_title', models.TextField(db_column='test item', verbose_name='Requirement title')),
                ('link', models.URLField()),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('test_method', models.TextField(verbose_name='Test Method')),
                ('requirement', models.TextField(verbose_name='Requirement')),
                ('protduct_scope', models.CharField(db_column='scope', max_length=100, verbose_name='Product Scope')),
                ('exemption', models.CharField(default='NA', max_length=30)),
                ('protocol_section', models.CharField(db_column='section', max_length=100)),
                ('mandatory_voluntary', models.CharField(db_column='restrict', max_length=30)),
                ('is_cornerstone', models.BooleanField(db_column='cornerstone', default=False, verbose_name='Is Cornerstone')),
                ('new_voluntary_safety_standard', models.TextField(db_column='new_restrict', null=True, verbose_name='New Voluntary Safety Standard')),
                ('reationale', models.CharField(max_length=50, null=True, verbose_name='Reationale')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Protocol Name')),
                ('life', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Protocols.Protocolid', verbose_name='Protocol Name'),
        ),
    ]
