# Generated by Django 2.1.7 on 2019-06-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReviewStage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfp', models.TextField(unique=True, verbose_name='Manufacturer Part Number')),
                ('pl_doc', models.TextField(verbose_name='PL Docs')),
                ('region', models.CharField(max_length=30, verbose_name='Active Region')),
                ('concession', models.TextField(verbose_name='Cocession Scenario')),
                ('approved_by', models.CharField(max_length=30, verbose_name='Approved By')),
                ('additional_notes', models.TextField(verbose_name='Additional Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Ocean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASIN', models.CharField(max_length=30)),
                ('on_sale', models.BooleanField(default=True)),
                ('marketplace', models.IntegerField()),
                ('risk_level', models.CharField(max_length=10)),
                ('vendor_type', models.CharField(max_length=15, verbose_name='ACD|vcd')),
                ('vendor_name', models.CharField(max_length=15, verbose_name='Vendor Code')),
                ('factory_name', models.CharField(max_length=30, verbose_name='Factory Name')),
                ('product_type', models.CharField(max_length=30, verbose_name='Product Type')),
                ('parent_asin', models.CharField(max_length=30, verbose_name='Parent Asin')),
                ('brand_name', models.CharField(max_length=30, verbose_name='Brand Name')),
                ('description', models.TextField(verbose_name='Product Description')),
            ],
        ),
        migrations.AddField(
            model_name='mfp',
            name='ASIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SamplingStage.Ocean'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='next_step',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mfp_next_step', to='ReviewStage.StatusAndNextStep'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='status',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mfp_status', to='ReviewStage.StatusAndNextStep'),
        ),
    ]
