# Generated by Django 2.1.7 on 2019-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_login', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('job_title', models.CharField(choices=[('C', 'C-Ops'), ('M', 'Manager'), ('AS', 'SME'), ('AC', 'C-Ops & Auditor'), ('D', 'Developer'), ('AD', 'Advanced User')], max_length=15, verbose_name='Job Title')),
            ],
        ),
    ]
